Fix labeler
actions/labeler pull request #405
Opened 2022-07-25 02:57 UTC by jsoref

Labeler has a bunch of more or less related problems.

* it doesn't properly annotate its `action.yml`
* it confuses booleans and strings #404 
* it doesn't handle permissions errors #136
* it's actively hostile to forks (#136)

The general implementation to address this fits the outlines in https://github.com/actions/labeler/issues/136#issuecomment-1169411989

https://github.com/check-spelling/use-labeler/actions/runs/2729552526
<img width="1300" alt="image" src="https://user-images.githubusercontent.com/2119212/180685825-bda43868-8e96-4cfb-a4e4-ab04622eb107.png">

Annotations
1 error and 1 warning
❌ [label](https://github.com/check-spelling/use-labeler/runs/7492592323?check_suite_focus=true#step:2:9)
Resource not accessible by integration
⚠️ [jsoref/labeler running under 'pull_request' is misconfigured](https://github.com/check-spelling/use-labeler/runs/7492592323?check_suite_focus=true#step:2:8)
It needs `permissions: pull-requests: write` to work. Update the workflow. See https://github.com/actions/labeler/blob/6a315d4ea58951035b498eef56668feaba24489f/README.md#create-workflow

---

https://github.com/check-spelling/use-labeler/runs/7492560360?check_suite_focus=true

Run jsoref/labeler@main
Workflow is not configured to label forks, exiting

This could include an info item, but, I don't really see the point.

---

2022-08-07 22:12 UTC, jsoref commented
@pje: is there something I need to do to push this along?

2022-08-22 11:27 UTC, jsoref commented
@thboop? I understand you're busy, but it'd be really helpful if someone would look (I can, of course, resolve conflicts, but it isn't worth it if no one will look at the PR.)

2022-09-20 04:51 UTC, Yaminyam commented
It is considered a very serious error to unintentionally delete a label in a tool for automating labeling.
I think that PR should be reflected quickly.

2022-09-30 21:10 UTC, ford-at-aws commented
👋  From AWS! We rely on this labeling solution and would love to see this bug worked out. Thanks!

2022-09-30 22:08 UTC, jsoref commented
@ford-at-aws I've enabled github actions on my fork: https://github.com/jsoref/labeler/actions -- and I've merged the changes into it.

<details><summary>Actions details for the relevant commits</summary>

✅ [Merge pull request #1 from jsoref/fix-labeler](https://github.com/jsoref/labeler/actions/runs/3161927607)
Build & Test #2: Commit [3cc0b12](https://github.com/jsoref/labeler/commit/3cc0b1265388e104c553c3c0d672c26009024e83) pushed by [jsoref](https://github.com/jsoref)
[main](https://github.com/jsoref/labeler)	

✅ [Fix labeler](https://github.com/jsoref/labeler/actions/runs/3161921541)
Build & Test #1: Pull request https://github.com/jsoref/labeler/pull/1 opened by [jsoref](https://github.com/jsoref)
[fix-labeler](https://github.com/jsoref/labeler/tree/fix-labeler)	

<img width="956" alt="image" src="https://user-images.githubusercontent.com/2119212/193362871-e74b27d4-2fa1-4f4a-9a5a-956a4ed5005e.png">

</details>

In theory where you would have used `actions/labeler@v4.0.1`, you could use `jsoref/labeler@v0-5.0.0`.
Or where you could have used `actions/labeler@e54e5b338fbd6e6cdb5d60f51c22335fc57c401e`, you could use `actions/labeler@6b5f93ed5fc722246dd157acf1984bb1e3065b4d`.

I will not delete the above tag. I can't delete the above commit sha -- do note that the sha doesn't (at the present time) refer to a commit in this repository, it's just https://github.com/jsoref/labeler/commit/6b5f93ed5fc722246dd157acf1984bb1e3065b4d, but by referencing this repository, you should be less sensitive to me renaming my repository (which I don't intend to ever do).

2022-10-03 13:44 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
Hi @jsoref do you think my issue https://github.com/actions/labeler/issues/442 is related?

2022-10-03 14:35 UTC, jsoref commented
@efb4f5ff-1298-471a-8973-3d47447115dc: dunno. I don't suppose you'd be willing to try using the labeler as versioned in https://github.com/actions/labeler/pull/405#issuecomment-1264073531 for a bit? I imagine you'd be able to confirm its behavior pretty quickly... You could even create a second copy (not really a fork, just a copy) of your repository w/ the alternate labeler and see how it behaves...

2022-12-20 14:28 UTC, jsoref commented
@MaksimZhukov can you look at this PR as well? At least one linked repository has been using this for months.

2023-06-13 13:25 UTC, AndreiLobanovich requested changes
Hello, @jsoref,

Thank you for your efforts and the time you have spent on creating this pull request. We appreciate contributors like you who are willing to dedicate their time to improving this project.
Some of the issues you are fixing have already been addressed in other pull requests:

1. The action.yml file is now properly annotated.
2. The issue with the `sync-labels` input has already been fixed in the new major release as it is a breaking change
3. As for the handling of permissions errors, it's important to note that the action is not designed to handle these errors. We have added a section in the README file to clarify this point.
4. With regard to your concern about the action being hostile to forks, we believe this is not the case, though we welcome further discussion on this point if you have additional concerns.

After reviewing your PR we came to the conclusion that we want to accept the change regarding the warning (the one I left comment for). Other changes are unnecessary.
We greatly appreciate your contribution and your patience through this process. We hope that this explanation provides clarity on our current position, and we certainly welcome future contributions from you.

2023-06-13 13:25 UTC, AndreiLobanovich commented on src/labeler.ts
> +          `It needs \`permissions: pull-requests: write\` to work. Update the workflow. See https://github.com/actions/labeler/blob/6a315d4ea58951035b498eef56668feaba24489f/README.md#create-workflow`
Could you please edit this warning the following way?
The action requires write permission to add labels to pull requests. For more information please refer to the action documentation: https://github.com/actions/labeler#permissions

2023-06-13 13:36 UTC, AndreiLobanovich commented on src/labeler.ts
> +          `It needs \`permissions: pull-requests: write\` to work. Update the workflow. See https://github.com/actions/labeler/blob/6a315d4ea58951035b498eef56668feaba24489f/README.md#create-workflow`
```suggestion
          `The action requires write permission to add labels to pull requests. For more information please refer to the action documentation: https://github.com/actions/labeler#permissions`,
```

2023-06-16 15:29 UTC, AndreiLobanovich approved these changes

2023-06-16 15:41 UTC, dsame approved these changes

2023-06-19 07:53 UTC, marko-zivic-93 approved these changes

2023-06-19 11:07 UTC, merged

2023-06-19 11:08 UTC, MaksimZhukov commented
@jsoref thank you for the contribution!